### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by broline** [broline/do-gains#1]
- [ ] add gulp watch
- [ ] wire up require and styles in content layout
- [ ] figure out what front end framework to use (react, jsblocks, angular, etc...)
- [ ] add some custom styles
